name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonar-analysis:
    name: Ejecutar análisis de SonarQube
    runs-on: ubuntu-latest

    steps:
      # 1. Obtener el código fuente del repositorio
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. (Opcional) Instalar dependencias adicionales si las requiere tu proyecto
      # Ejemplo: configurar Java o cualquier otra herramienta necesaria.

      # 3. Ejecutar Sonar Scanner utilizando Docker
      - name: Ejecutar Sonar Scanner
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
            -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            -w /usr/src \
            sonarsource/sonar-scanner-cli:latest